# Week 2 Lecture
We will review Chapter 3, 4 and 5 in this lecture series.  Last week, we talked about basic Python code.  We will continue in this lecture to add to <br>
what we know. Let's first run the code cell below.

In [1]:
from datascience import *
import numpy as np
%matplotlib inline
import matplotlib.pyplot as plots
plots.style.use('fivethirtyeight')
import warnings
warnings.simplefilter(action="ignore", category=FutureWarning)

from urllib.request import urlopen 
import re
def read_url(url): 
    return re.sub('\\s+', ' ', urlopen(url).read().decode())

# Expression
We will review expressions from Chapter 3.1

| Expression Type | Operator | Example  | Value   |
|-----------------|----------|----------|---------|
| Addition        | +        | 2 + 3    | 5       |
| Subtraction     | -        | 2 - 3    | -1      |
| Multiplication  | *        | 2 * 3    | 6       |
| Division        | /        | 7/3      | 2.66667 |
| Remainder       | %        | 7 % 3    | 1       |
| Exponentiation  | **       | 2 ** 0.5 | 1.41421 |

## PEMDAS - Order of Operations
- Paretheses
- Exponents
- Multiplication and Division left to right
- Addition and Subtraction left to right

```
1 + 2 * 3 * 4 * 5 / 6 ** 3 + 7 + 8 - 9 + 10
1 + 2 * 3 * 4 * 5 / 216 + 7 + 8 - 9 + 10
1 + 6 * 4 * 5 / 216 + 7 + 8 - 9 + 10
1 + 24 * 5 / 216 + 7 + 8 - 9 + 10
1 + 120 / 216 + 7 + 8 - 9 + 10
1 + 0.555555555555557 + 7 + 8 - 9 + 10
1.555555555555557 + 7 + 8 - 9 + 10
8.555555555555557 + 8 - 9 + 10
16.555555555555557 - 9 + 10
7.555555555555557 + 10
17.555555555555557
```

In [10]:
1 + 2 * 3 * 4 * 5 / 6 ** 3 + 7 + 8 - 9 + 10

17.555555555555557

In [2]:
2+3

5

In [3]:
2 - 3

-1

In [4]:
2*3

6

In [5]:
7/3

2.3333333333333335

In [6]:
7%3

1

In [9]:
2 ** 4

16

In [ ]:
1 + 2 * 3 * 4 * 5 / 6 ** 3 + 7 + 8 - 9 + 10

# Names
Names that hold numeric or text values.  Names must begin with a letter or _ (underscore).  However, in this course, names will start with a letter.  You assign a value or string to a name using the = symbol

- quarter = 1/4
- half = 2 * quarter
- firstName = 'JoEllen'  

firstName variable name is called camel because the Name is capitolized.  Using first_name can be another way to write a name.  Each name firstname, firstName, and first_Name are all different variable names.

```
firstname = 'JoEllen'
firstName = 'Amy'
first_Name = 'Will'
print(firstname)
print(firstName)
print(first_Name)
```


In [15]:
firstname = 'JoEllen'
firstName = 'Amy'
first_Name = "Will"
print(firstname)
print(firstName)
print(first_Name)

JoEllen
Amy
Will


In [16]:
firstName = "JoEllen"
print("My firstname is",firstname,".")

My firstname is JoEllen .


# Using variables to do calculations

```
hours = 40
rates = 25.5
weeks = hours * rates
print("She earned $', weeks,"this week.")
```

In [18]:
hours = 40
rates = 25.5
weeks = hours * rates
print("She earned $", weeks,"this week.")

She earned $ 1020.0 this week.


# Growth Rates
Growth_rate = (changed - initial)/initial another way to define the growth rate<br>
Growth_rate = (changed/initial) - 1



In [20]:
changed = 130312
initial = 80000
Growth_rate = (changed - initial)/initial
Growth_rate


0.6289

In [22]:
Growth_rate_1 = (changed/initial) - 1
Growth_rate_1

0.6289

# Growth Rate give constant growth rate
```
annual_growth_rate = 0.05
ten_year_growth_rate = (1 + annual_growth_rate)**10 - 1
print("Ten year rate = ", ten_year_growth_rate)
print("Ten year growth rate", GrowthRate)
```
Like wise if I look at an initial amount and then the changed amount you can figure out the annual growth rate by knowing the number of years in between.
```
initial = 80000
changed = 130312
n = 10
annual_Growth_Rate = (changed/initial)**(1/n) - 1
annual_Growth_rate
```

In [25]:
annual_growth_rate = 0.05
ten_year_growth_rate = (1 + annual_growth_rate)**10 - 1
print("Ten year rate = ", ten_year_growth_rate)
print("Ten year growth rate", Growth_rate)

Ten year rate =  0.628894626777442
Ten year growth rate 0.6289


# Call Expressions
Call expressions invoke functions<br>
[List of Python functions](https://docs.python.org/3/library/functions.html)
There are functions that are not defaults but belong to other libraries.  To access those functions use the code below.
```
import math
import operator
math.sqrt(operator.add(4, 5))
```

In [26]:
import math
import operator

In [28]:
math.ceil(4.04)

5

# Help function
To get information on a function.
```
math.log?

max?
```


In [29]:
math.log?

Docstring:
log(x, [base=math.e])
Return the logarithm of x to the given base.

If the base not specified, returns the natural logarithm (base e) of x.
Type:      builtin_function_or_method

In [30]:
math.log(16, 3)

2.5237190142858297

In [31]:
math.remainder?

Signature: math.remainder(x, y, /)
Docstring:
Difference between x and the closest integer multiple of y.

Return x - n*y where n*y is the closest integer multiple of y.
In the case where x is exactly halfway between two multiples of
y, the nearest even value of n is used. The result is always exact.
Type:      builtin_function_or_method

In [33]:
math.remainder(40, 6)

-2.0

# Tables
Tables is like a spreadsheet of data with each column having a name and data in each column.  The data can be numeric or string (Text).<br>
Below I am creating a table with three columns Flavor, Color, and Price.  You will learn the code later in the course.

In [34]:
# Introduction to Tables
cones = Table().with_columns(
                       'Flavor', make_array('strawberry', 'chocolate', 'chocolate', 'strawberry', 'chocolate', 'bubblegum'),
                        'Color', make_array('pink', 'light brown', 'dark brown', 'pink', 'dark brown', 'pink'),
                        'Price', make_array(3.55, 4.75, 5.25, 5.25, 5.25, 4.75)
)


In [35]:
# Display the table by entering the table name
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

# Methods

table_name.method(arguments)<br>

the show method will show the first n rows of the table
```
table_name.show(n)
```
In the cell below show 2 records of the cones table.<br>
[Table methods](https://www.data8.org/datascience/reference-nb/datascience-reference.html)

In [37]:
n =  12   # the number of records to show 
cones.show(n)

In [38]:
cones.num_rows

6

In [39]:
cones.num_columns

3

# Selecting columns in Table
When you use the select method with the table name you create a subset of the table with the columns you selected.  The original table is not affected.<br><br>

table_name.select('column name')<br>
table_name.select('column_name_1', 'column_name_2')

In [40]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [41]:
cones.select('Flavor')

Flavor
strawberry
chocolate
chocolate
strawberry
chocolate
bubblegum

In [42]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [45]:
iceCreamPrices = cones.select('Flavor', 'Price')
iceCreamPrices

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

# Drop a column
Sometimes you may want to a table without one of the columns.  In that case, you would use the drop method.  The original table is not affected.<br>
```
tablename.drop('column_name')
```
The resulting table does not change the original table.

In [47]:
cones.drop('Color')

Flavor     | Price
strawberry | 3.55
chocolate  | 4.75
chocolate  | 5.25
strawberry | 5.25
chocolate  | 5.25
bubblegum  | 4.75

# Sorting Rows
Sorts the table based on the rows in a column.
```
table_name.sort('column_name')  # smallest to largest
table_name.sort('column_name', descending = True)
```
Sort the cones table by Price

In [48]:
cones

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
bubblegum  | pink        | 4.75

In [49]:
cones.sort('Flavor')

Flavor     | Color       | Price
bubblegum  | pink        | 4.75
chocolate  | light brown | 4.75
chocolate  | dark brown  | 5.25
chocolate  | dark brown  | 5.25
strawberry | pink        | 3.55
strawberry | pink        | 5.25

In [50]:
cones.sort('Price')

Flavor     | Color       | Price
strawberry | pink        | 3.55
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25

In [51]:
cones.sort('Price', descending=True)

Flavor     | Color       | Price
chocolate  | dark brown  | 5.25
strawberry | pink        | 5.25
chocolate  | dark brown  | 5.25
chocolate  | light brown | 4.75
bubblegum  | pink        | 4.75
strawberry | pink        | 3.55

# Selecting Rows that satisfy Conditions
```
table_name.where('columnName', 'value')
```
Select chocolate records for the table cones.  Make sure the value is listed in the table.  Otherwise, it will not show anything.


In [52]:
cones.where('Flavor', 'chocolate')

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

In [54]:
cones.where('Flavor', 'chocolate')

Flavor    | Color       | Price
chocolate | light brown | 4.75
chocolate | dark brown  | 5.25
chocolate | dark brown  | 5.25

In [57]:
nba = Table().read_table('nba_salaries.csv')

In [59]:
nba

rank | name             | position | team                   | salary   | season
1    | Shaquille O'Neal | C        | Los Angeles Lakers     | 17142000 | 2000
2    | Kevin Garnett    | PF       | Minnesota Timberwolves | 16806000 | 2000
3    | Alonzo Mourning  | C        | Miami Heat             | 15004000 | 2000
4    | Juwan Howard     | PF       | Washington Wizards     | 15000000 | 2000
5    | Scottie Pippen   | SF       | Portland Trail Blazers | 14795000 | 2000
6    | Karl Malone      | PF       | Utah Jazz              | 14000000 | 2000
7    | Larry Johnson    | F        | New York Knicks        | 11910000 | 2000
8    | Gary Payton      | PG       | Seattle SuperSonics    | 11020000 | 2000
9    | Rasheed Wallace  | PF       | Portland Trail Blazers | 10800000 | 2000
10   | Shawn Kemp       | C        | Cleveland Cavaliers    | 10780000 | 2000
... (9446 rows omitted)

In [60]:
nba.sort('team')

rank | name            | position | team          | salary  | season
40   | Alan Henderson  | PF       | Atlanta Hawks | 5318000 | 2000
57   | Lorenzen Wright | PF       | Atlanta Hawks | 4400000 | 2000
117  | Chris Crawford  | SF       | Atlanta Hawks | 2000000 | 2000
129  | Jason Terry     | G        | Atlanta Hawks | 1468000 | 2000
141  | Cal Bowdler     | F        | Atlanta Hawks | 1025000 | 2000
145  | Roshown McLeod  | F        | Atlanta Hawks | 914000  | 2000
146  | Dion Glover     | SG       | Atlanta Hawks | 893000  | 2000
66   | Alan Henderson  | PF       | Atlanta Hawks | 5909000 | 2001
89   | Lorenzen Wright | PF       | Atlanta Hawks | 4950000 | 2001
189  | Chris Crawford  | SF       | Atlanta Hawks | 2250000 | 2001
... (9446 rows omitted)

In [61]:
warriors = nba.where('team', 'Golden State Warriors')

In [63]:
warriors.show()

In [64]:
warriors.relabel('salary', 'Salary')

rank | name              | position | team                  | Salary  | season
41   | Donyell Marshall  | PF       | Golden State Warriors | 5250000 | 2000
47   | Erick Dampier     | C        | Golden State Warriors | 4988000 | 2000
58   | Mookie Blaylock   | G        | Golden State Warriors | 4200000 | 2000
59   | Chris Mills       | SF       | Golden State Warriors | 4200000 | 2000
64   | Jason Caffey      | F        | Golden State Warriors | 3937000 | 2000
89   | Vonteego Cummings | PG       | Golden State Warriors | 2600000 | 2000
92   | Antawn Jamison    | PF       | Golden State Warriors | 2503000 | 2000
73   | Erick Dampier     | C        | Golden State Warriors | 5611000 | 2001
91   | Mookie Blaylock   | G        | Golden State Warriors | 4800000 | 2001
92   | Chris Mills       | SF       | Golden State Warriors | 4800000 | 2001
... (301 rows omitted)

In [65]:
warriors.relabel('team', 'TEAM')

rank | name              | position | TEAM                  | Salary  | season
41   | Donyell Marshall  | PF       | Golden State Warriors | 5250000 | 2000
47   | Erick Dampier     | C        | Golden State Warriors | 4988000 | 2000
58   | Mookie Blaylock   | G        | Golden State Warriors | 4200000 | 2000
59   | Chris Mills       | SF       | Golden State Warriors | 4200000 | 2000
64   | Jason Caffey      | F        | Golden State Warriors | 3937000 | 2000
89   | Vonteego Cummings | PG       | Golden State Warriors | 2600000 | 2000
92   | Antawn Jamison    | PF       | Golden State Warriors | 2503000 | 2000
73   | Erick Dampier     | C        | Golden State Warriors | 5611000 | 2001
91   | Mookie Blaylock   | G        | Golden State Warriors | 4800000 | 2001
92   | Chris Mills       | SF       | Golden State Warriors | 4800000 | 2001
... (301 rows omitted)

In [66]:
warriors.sort('Salary', descending=True)

rank | name           | position | TEAM                  | Salary   | season
1    | Stephen Curry  | PG       | Golden State Warriors | 40231758 | 2020
1    | Stephen Curry  | PG       | Golden State Warriors | 37457154 | 2018
1    | Stephen Curry  | PG       | Golden State Warriors | 37457154 | 2019
13   | Klay Thompson  | SG       | Golden State Warriors | 32742000 | 2020
11   | Kevin Durant   | SF       | Golden State Warriors | 30000000 | 2019
5    | Kevin Durant   | SF       | Golden State Warriors | 26540100 | 2017
51   | Klay Thompson  | SG       | Golden State Warriors | 18988725 | 2019
60   | Draymond Green | PF       | Golden State Warriors | 18539130 | 2020
53   | Klay Thompson  | SG       | Golden State Warriors | 17826150 | 2018
55   | Draymond Green | PF       | Golden State Warriors | 17469565 | 2018
... (301 rows omitted)

# Relabel a column
Sometimes we need to relabel a column we can use the following code to relabel the column
```
table_name.relabel('old column name', 'new column name')
```

# Sorting dolumns

```
table_name.sort('column name', descending = True)
```

In [ ]:
warriors.sort('SALARY', descending=True)

# Data Types
There are a number of different data types when storing data.  For example, string, numbers(float and integer), and DateTime.<br>
To find the data type, you can use the function type(abs).<br>

## Integers - int - negative and positive whole numbers.

h = 2<br>
t = -1<br>
3 ** 2034  <br>

## Real- float - All numbers, integers, and values between two integers.

y = 2.5<br>
w = 1.33333333333333333<br>
z = 10/6

## String - Text
name = "JoEllen Green"
statement = "My class's name is Introduction to Data Science"


## Data Type function

type(h)<br>
type(t)<br>
type(y)<br>
type(w)<br>
type(z)<br>
type(name)<br>
type(statement)<br>

In the code cell below, create the variable names above.  Then, create five code cells and enter the type functions above to determine each variable's data type.


In [67]:
h = 2
t = -1
u = 3 ** 2034

In [68]:
print(type(h))
print(type(t))
print(type(u))

<class 'int'>
<class 'int'>
<class 'int'>


In [69]:
u

29149566452602304440763736492336811556296148294918530051054540450336025231900797898436097427354911676832362421358904899228129875444470030145576732293526750734488432098290644721593482057168083076017653912310104408329210309447423391509449599012860981042395247599700811191043386239589821074771470127148712900007558438292144921153545313446749024529090193378048696732656110598766125542357261905576294353286842154420308454421479056397907148404044328573309940499007285529088186153114419908114622181325945450613738811723448644185914068943480418659928040430478148569961370776485275140784600966573147541829345309163253896126244591156200912921485144585830001308424166856921682196318815834990860169037547366579092871058416134931391781960705364316646720894109447082484004579160879818441449223358818917040453599207539194794148709975598511424671418826062131994246550577459770382337616816033832452449783395640722413752897820006026502105409138163201011087517131185148146602594083580026569

# Float Values
- Extremely Large or Extremely small numbers.
- 15 or 16 significant digits.
- When performing arithmetic the last few digits may be incorrect.

In [70]:
y = 2.5
w = 1.33333333333333333
z = 10/6

In [71]:
print(type(y))
print(type(w))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>


In [72]:
2.1**132
3.4115120127810504 x 10**42

3.4115120127810504e+42

In [75]:
1/23456789012345

4.263158096676033e-14

In [74]:
3.4115120127810504 * 10**42

3.4115120127810504e+42

In [76]:
56/8

7.0

In [77]:
type(56/8)

float

# Strings variables 
String variables are alphanumeric and special characteristic values.<br>
You can use the + symbol to combine string values or variables.<br>

"data" + "science"<br>
Answer: 'datascience'<br><br>
'data' + " " + 'science'<br>
Answer: 'data science'<br>

## Changing number to string
"That's "+ str(1 + 1) +" ' + str(True)<br>
Answer: "That's 2 True"<br><br>

In the code cells below, enter the string statement above and verify the answers.


In [78]:
"data" + "science"

'datascience'

In [79]:
'data' + " " + "science"

'data science'

In [80]:
myname = "JoEllen"+" "+"Green"

'JoEllen Green'

In [82]:
myname = "JoEllen"+" "+"Green"
print(myname)

JoEllen Green


# String Methods
There are methods that strings can use to make changes to it.  For example, uppercase, lowercase, and replace<br>
__[String Methods](https://www.w3schools.com/python/python_ref_string.asp)__
<br><br>
"load".upper()  # makes the string uppercase<br>
"hitchhiker".replace("hi", "ma") # replace hi with ma so the result will be matchhiker<br>
s = 'train'<br>
t = s.replace('t', 'ing')<br>
u = t.replace('in', 'de')<br>
u<br>
Answer: 'degrade'<br>
<br>
In the code cell, s = 'train', then replace 'ain' with 'ought'.  Display the answer.<br>

In [83]:
s = 'train'

In [84]:
s.upper()

'TRAIN'

In [85]:
s.lower()

'train'

In [86]:
s.replace('t', 'ing')

'ingrain'

In [88]:
t = s.replace('t', 'ing')
t

'ingrain'

In [89]:
s

'train'

In [90]:
u = t.replace('in', 'de')
u

'degrade'

# Comparisons
Logical comparison results are either True or False.

| **Comparison**     | **Operator** | **True Example** | **False Example** |
|--------------------|--------------|------------------|-------------------|
| Less than           | <            | 2 < 3            | 2 < 2             |
| Greater than       | >            | 3 > 2            | 3 > 3             |
| Less than or equal | <=           | 2 <= 2           | 3 <= 2            |
| Greater or equal   | >=           | 3 >= 3           | 2 >= 3            |
| Equal              | ==           | 3 == 3           | 3 == 2            |
| Not equal          | !=           | 3 != 2           | 2 != 2            |

In [91]:
2<3

True

In [92]:
2<2

False

In [93]:
2<=2

True

In [94]:
3 <= 4

True

In [95]:
5 <= 3

False

In [96]:
10 > 7

True

In [97]:
10 >= 10

True

In [98]:
23 != 49

True

In [99]:
24 == 24

True

In [100]:
24 == 25

False

# Multiple comparisons

1 < 1 + 1 < 3

In [101]:
1 < 1 + 1 < 3

True

In [102]:
x = 12
y = 5 
min(x, y) <= (x + y)/2 <= max(x, y)

True

In [103]:
min(x,y)

5

In [104]:
(x+y)/2

8.5

In [105]:
max(x, y)

12

# you can compare strings
"Dog" > "Catashtrope" > "Cat"

In [106]:
"Dog" > "Catashtrope" > "Cat"

True

# Arrays
List of numbers or strings<br>

```
h = make_array(3, 4, 5, 6, 7, 8, 9)
h
```

In [107]:
h = make_array(3, 4, 5, 6, 7, 8, 9)
h

array([3, 4, 5, 6, 7, 8, 9])

In [108]:
h*2

array([ 6,  8, 10, 12, 14, 16, 18])

In [109]:
h**2

array([ 9, 16, 25, 36, 49, 64, 81])

In [110]:
highs= make_array(14.88 - 0.880, 14.88 - 0.093, 14.88 + 0.105, 14.88 + 0.684)
highs

array([ 14.   ,  14.787,  14.985,  15.564])

In [111]:
(9/5)*highs + 32

array([ 57.2   ,  58.6166,  58.973 ,  60.0152])

In [112]:
import numpy as np

# full Numpy reference
To find a reference to functions in the Numpy library use the link below.<br>
[Numpy reference website](https://numpy.org/doc/stable/reference/)

| Function         | Description                                                           |
|------------------|-----------------------------------------------------------------------|
| np.prod          | Multiply all elements together                                        |
| np.sum           | Add all elements together                                             |
| np.all           | Test whether all elements are true values (non-zero numbers are true) |
| np.any           | Test whether any elements are true values (non-zero numbers are true) |
| np.count_nonzero | Count the number of non-zero elements                                 |
The functions above have no elements in the parentheses. Such as <br>
```
highs.prod()
```
    

In [113]:
yint = make_array(1, 2, 3, 4)
yint

array([1, 2, 3, 4])

In [114]:
np.prod(yint)

24

In [115]:
np.sum(yint)

10

In [116]:
np.all(yint)

True

In [117]:
np.any(yint)

True

In [118]:
np.count_nonzero(yint)

4

# Function with arguments
| Function   | Description                                                          |
|------------|----------------------------------------------------------------------|
| np.diff    | Difference between adjacent elements                                 |
| np.round   | Round each number to the nearest intege(whole number)                |
| np.cumprod | A cumulative product: for each element, multiply all elements so far |
| np.cumsum  | A cumulative sum: for each element, add all elements so far          |
| np.exp     | Exponentiate each element                                            |
| np.log     | Take the natural logarithm of each element                           |
| np.sqrt    | Take the square root of each element                                 |
| np.sort    | Sort the elements                                                    |

```
np.sort(highs)
```
**Answer**<br>
array([ 13.6  ,  14.387,  14.585,  15.164])

In [119]:
yint

array([1, 2, 3, 4])

In [121]:
np.diff(yint)

array([1, 1, 1])

In [122]:
wint = make_array(45.6897, 56.2395, 36.8923, 45.0123)

In [123]:
np.round(wint, 2)

array([ 45.69,  56.24,  36.89,  45.01])

In [124]:
np.cumprod(yint)

array([ 1,  2,  6, 24])

In [125]:
np.exp(yint)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

In [126]:
np.log(yint)

array([ 0.        ,  0.69314718,  1.09861229,  1.38629436])

In [127]:
np.sqrt(yint)

array([ 1.        ,  1.41421356,  1.73205081,  2.        ])

In [128]:
np.sort(wint)

array([ 36.8923,  45.0123,  45.6897,  56.2395])

In [130]:
np.sort?

Signature:       np.sort(a, axis=-1, kind=None, order=None, *, stable=None)
Call signature:  np.sort(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function sort at 0x7d649853a020>
File:            /srv/conda/envs/notebook/lib/python3.11/site-packages/numpy/_core/fromnumeric.py
Docstring:      
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and,
    in general, the actual implementation will vary with data type.
    The 'mergesort' option is retained for backwards compatibility.
order : str or list of str, optional
    When `a` is an array with fie